<?php
defined('APPLICATION_PATH') OR exit('No direct script access allowed');

$error = array(
    'express_lack_of_com_error' => array('errcode'=>1,'errmsg'=>'请选择快递公司名称'),
    'express_lack_of_nu_error' => array('errcode'=>2,'errmsg'=>'请输入快递单号'),
    'music_lack_of_hash_error' => array('errcode'=>4,'errmsg'=>'缺少音乐hash'),
    'music_lack_of_name_error' => array('errcode'=>5,'errmsg'=>'请输入音乐信息'),
    'ssq_got_price_before' => array('errcode'=>6,'errmsg'=>'此号码已中大奖'),
    'stock_lack_of_stockid_error' => array('errcode'=>7,'errmsg'=>'请输入股票diamante'),
    'weather_lack_of_cityid_error' => array('errcode'=>8,'errmsg'=>'请选择城市'),
    'get_lottery_no_result_found' => array('errcode'=>9,'errmsg'=>'未查询到开奖信息'),
    'request_not_allowed' => array('errcode'=>10,'errmsg'=>'请求非法'),
    'email_must_be_array' => array('errcode'=>11, 'errmsg'=>'The email validation method must be passed an array.'),
    'email_invalid_address' => array('errcode'=>12, 'errmsg'=>'Invalid email address: %s'),
    'email_attachment_missing' => array('errcode'=>13, 'errmsg'=>'Unable to locate the following email attachment: %s'),
    'email_attachment_unreadable' => array('errcode'=>14, 'errmsg'=>'Unable to open this attachment: %s'),
    'email_no_from' => array('errcode'=>15, 'errmsg'=>'Cannot send mail with no "From" header.'),
    'email_no_recipients' => array('errcode'=>16, 'errmsg'=>'You must include recipients: To, Cc, or Bcc'),
    'email_send_failure_phpmail' => array('errcode'=>17, 'errmsg'=>'Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.'),
    'email_send_failure_sendmail' => array('errcode'=>18, 'errmsg'=>'Unable to send email using PHP Sendmail. Your server might not be configured to send mail using this method.'),
    'email_send_failure_smtp' => array('errcode'=>19, 'errmsg'=>'Unable to send email using PHP SMTP. Your server might not be configured to send mail using this method.'),
    'email_sent' => array('errcode'=>20, 'errmsg'=>'Your message has been successfully sent using the following protocol: %s'),
    'email_no_socket' => array('errcode'=>21, 'errmsg'=>'Unable to open a socket to Sendmail. Please check settings.'),
    'email_no_hostname' => array('errcode'=>22, 'errmsg'=>'You did not specify a SMTP hostname.'),
    'email_smtp_error' => array('errcode'=>23, 'errmsg'=>'The following SMTP error was encountered: %s'),
    'email_no_smtp_unpw' => array('errcode'=>24, 'errmsg'=>'Error: You must assign a SMTP username and password.'),
    'email_failed_smtp_login' => array('errcode'=>25, 'errmsg'=>'Failed to send AUTH LOGIN command. Error: %s'),
    'email_smtp_auth_un' => array('errcode'=>26, 'errmsg'=>'Failed to authenticate username. Error: %s'),
    'email_smtp_auth_pw' => array('errcode'=>27, 'errmsg'=>'Failed to authenticate password. Error: %s'),
    'email_smtp_data_failure' => array('errcode'=>28, 'errmsg'=>'Unable to send data: %s'),
    'email_exit_status' => array('errcode'=>29, 'errmsg'=>'Exit status code: %s'),
);
