<?php
defined('APPLICATION_PATH') OR exit('No direct script access allowed');

$error = array(
    'express_lack_of_com_error' => array('errcode'=>1,'errmsg'=>'请选择快递公司名称'),
    'express_lack_of_nu_error' => array('errcode'=>2,'errmsg'=>'请输入快递单号'),
    'music_lack_of_hash_error' => array('errcode'=>4,'errmsg'=>'缺少音乐hash'),
    'music_lack_of_name_error' => array('errcode'=>5,'errmsg'=>'请输入音乐信息'),
    'ssq_got_price_before' => array('errcode'=>6,'errmsg'=>'此号码已中大奖'),
    'stock_lack_of_stockid_error' => array('errcode'=>7,'errmsg'=>'请输入股票diamante'),
    'weather_lack_of_cityid_error' => array('errcode'=>8,'errmsg'=>'请选择城市'),
    'get_lottery_no_result_found' => array('errcode'=>9,'errmsg'=>'未查询到开奖信息'),
    'request_not_allowed' => array('errcode'=>10,'errmsg'=>'请求非法'),
    'email_must_be_array' => array('errcode'=>11, 'errmsg'=>'The email validation method must be passed an array.'),
    'email_invalid_address' => array('errcode'=>12, 'errmsg'=>'Invalid email address: %s'),
    'email_attachment_missing' => array('errcode'=>13, 'errmsg'=>'Unable to locate the following email attachment: %s'),
    'email_attachment_unreadable' => array('errcode'=>14, 'errmsg'=>'Unable to open this attachment: %s'),
    'email_no_from' => array('errcode'=>15, 'errmsg'=>'Cannot send mail with no "From" header.'),
    'email_no_recipients' => array('errcode'=>16, 'errmsg'=>'You must include recipients: To, Cc, or Bcc'),
    'email_send_failure_phpmail' => array('errcode'=>17, 'errmsg'=>'Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.'),
    'email_send_failure_sendmail' => array('errcode'=>18, 'errmsg'=>'Unable to send email using PHP Sendmail. Your server might not be configured to send mail using this method.'),
    'email_send_failure_smtp' => array('errcode'=>19, 'errmsg'=>'Unable to send email using PHP SMTP. Your server might not be configured to send mail using this method.'),
    'email_sent' => array('errcode'=>20, 'errmsg'=>'Your message has been successfully sent using the following protocol: %s'),
    'email_no_socket' => array('errcode'=>21, 'errmsg'=>'Unable to open a socket to Sendmail. Please check settings.'),
    'email_no_hostname' => array('errcode'=>22, 'errmsg'=>'You did not specify a SMTP hostname.'),
    'email_smtp_error' => array('errcode'=>23, 'errmsg'=>'The following SMTP error was encountered: %s'),
    'email_no_smtp_unpw' => array('errcode'=>24, 'errmsg'=>'Error: You must assign a SMTP username and password.'),
    'email_failed_smtp_login' => array('errcode'=>25, 'errmsg'=>'Failed to send AUTH LOGIN command. Error: %s'),
    'email_smtp_auth_un' => array('errcode'=>26, 'errmsg'=>'Failed to authenticate username. Error: %s'),
    'email_smtp_auth_pw' => array('errcode'=>27, 'errmsg'=>'Failed to authenticate password. Error: %s'),
    'email_smtp_data_failure' => array('errcode'=>28, 'errmsg'=>'Unable to send data: %s'),
    'email_exit_status' => array('errcode'=>29, 'errmsg'=>'Exit status code: %s'),
    'youtu_api_not_supported' => array('errcode'=>30, 'errmsg'=>'youtu api not supported'),
    
    'upload_userfile_not_set' => array('errcode'=>31, 'errmsg'=>'Unable to find a post variable called userfile.'),
    'upload_file_exceeds_limit' => array('errcode'=>32, 'errmsg'=>'The uploaded file exceeds the maximum allowed size in your PHP configuration file.'),
    'upload_file_exceeds_form_limit' => array('errcode'=>33, 'errmsg'=>'The uploaded file exceeds the maximum size allowed by the submission form.'),
    'upload_file_partial' => array('errcode'=>34, 'errmsg'=>'The file was only partially uploaded.'),
    'upload_no_temp_directory' => array('errcode'=>35, 'errmsg'=>'The temporary folder is missing.'),
    'upload_unable_to_write_file' => array('errcode'=>36, 'errmsg'=>'The file could not be written to disk.'),
    'upload_stopped_by_extension' => array('errcode'=>37, 'errmsg'=>'The file upload was stopped by extension.'),
    'upload_no_file_selected' => array('errcode'=>38, 'errmsg'=>'You did not select a file to upload.'),
    'upload_invalid_filetype' => array('errcode'=>39, 'errmsg'=>'The filetype you are attempting to upload is not allowed.'),
    'upload_invalid_filesize' => array('errcode'=>40, 'errmsg'=>'The file you are attempting to upload is larger than the permitted size.'),
    'upload_invalid_dimensions' => array('errcode'=>41, 'errmsg'=>'The image you are attempting to upload doesn\'t fit into the allowed dimensions.'),
    'upload_destination_error' => array('errcode'=>42, 'errmsg'=>'A problem was encountered while attempting to move the uploaded file to the final destination.'),
    'upload_no_filepath' => array('errcode'=>43, 'errmsg'=>'The upload path does not appear to be valid.'),
    'upload_no_file_types' => array('errcode'=>44, 'errmsg'=>'You have not specified any allowed file types.'),
    'upload_bad_filename' => array('errcode'=>45, 'errmsg'=>'The file name you submitted already exists on the server.'),
    'upload_not_writable' => array('errcode'=>46, 'errmsg'=>'The upload destination folder does not appear to be writable.'),
    'image_url_empty' => array('errcode'=>47, 'errmsg'=>'The image url cannot be empty.'),
    
    
    'service_unavailable' => array('errcode'=>48, 'errmsg'=>'service is unavailable now, please try later.'),
    
    'imglib_source_image_required' => array('errcode'=>49, 'errmsg'=>'You must specify a source image in your preferences.'),
    'imglib_gd_required' => array('errcode'=>50, 'errmsg'=>'The GD image library is required for this feature.'),
    'imglib_gd_required_for_props' => array('errcode'=>51, 'errmsg'=>'Your server must support the GD image library in order to determine the image properties.'),
    'imglib_unsupported_imagecreate' => array('errcode'=>52, 'errmsg'=>'Your server does not support the GD function required to process this type of image.'),
    'imglib_gif_not_supported' => array('errcode'=>53, 'errmsg'=>'GIF images are often not supported due to licensing restrictions. You may have to use JPG or PNG images instead.'),
    'imglib_jpg_not_supported' => array('errcode'=>54, 'errmsg'=>'JPG images are not supported.'),
    'imglib_png_not_supported' => array('errcode'=>55, 'errmsg'=>'PNG images are not supported.'),
    'imglib_jpg_or_png_required' => array('errcode'=>56, 'errmsg'=>'The image resize protocol specified in your preferences only works with JPEG or PNG image types.'),
    'imglib_copy_error' => array('errcode'=>57, 'errmsg'=>'An error was encountered while attempting to replace the file. Please make sure your file directory is writable.'),
    'imglib_rotate_unsupported' => array('errcode'=>58, 'errmsg'=>'Image rotation does not appear to be supported by your server.'),
    'imglib_libpath_invalid' => array('errcode'=>59, 'errmsg'=>'The path to your image library is not correct. Please set the correct path in your image preferences.'),
    'imglib_image_process_failed' => array('errcode'=>60, 'errmsg'=>'Image processing failed. Please verify that your server supports the chosen protocol and that the path to your image library is correct.'),
    'imglib_rotation_angle_required' => array('errcode'=>61, 'errmsg'=>'An angle of rotation is required to rotate the image.'),
    'imglib_invalid_path' => array('errcode'=>62, 'errmsg'=>'The path to the image is not correct.'),
    'imglib_copy_failed' => array('errcode'=>63, 'errmsg'=>'The image copy routine failed.'),
    'imglib_missing_font' => array('errcode'=>64, 'errmsg'=>'Unable to find a font to use.'),
    'imglib_save_failed' => array('errcode'=>65, 'errmsg'=>'Unable to save the image. Please make sure the image and file directory are writable.'),


    'image_get_from_oss_error' => array('errcode'=>66, 'errmsg'=>'Get image from oss failed.'),
);
